### PR TITLE
Continue App init when Login timeouts

### LINKED ISSUE #225: Generator only allows logged in user
### Expected Behaviour

```
aio app init
```
should prompt me to log in. but if I don't have an Adobe ID, I should still be able to continue with this flow. 

### Actual Behaviour

Generator does not allow me to not log in. Times out if the user is not logged in. 

```
aio app init
Visit this url to log in: 
https://aio-login.adobeioruntime.net/api/v1/web/default/applogin?id=89125e9f&port=52227
Error: Timed out after 120 seconds.
    at Timeout._onTimeout (~/.local/share/@adobe/aio-cli/node_modules/@adobe/aio-lib-ims-oauth/src/login.js:51:14)
```

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
Continue App init when Login timeouts.
Skip console generator in this case.
Fixes #225 

## How Has This Been Tested?
manual run and unit tests
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/commands/app/init.js [hunk 1]
```diff
@@ -38,20 +38,30 @@ class InitCommand extends BaseCommand {
...
-        const generatedFile = 'console.json'
-        env.register(require.resolve('@adobe/generator-aio-console'), 'gen-console')
-        res = await env.run('gen-console', {
-          'destination-file': generatedFile,
-          'access-token': accessToken,
-          'ims-env': imsEnv
-        })
-        // trigger import
-        flags.import = generatedFile
+        const { accessToken, env: imsEnv } = await getCliInfo()
```
Comment (shazron) [inline src/commands/app/init.js:44]: I'm confused why you just didn't take this line and just put in the bottom try catch, without resulting in this extra code. Having a custom error message is irrelevant.

Comment (sandeep-paliwal) [reply src/commands/app/init.js:44]: OK. I thought in this case it would be good to log custom error. Anyway I can move this to the other try catch block
