### PR TITLE
Hook errors#665

### LINKED ISSUE #665: plugin hook errors are ignored
**Describe the bug**
When a we fire an oclif hook event it is handled by one or more cli plugin hook responder.  If any of these hook responders encounters an error, it cannot exit the app and any exception it throws is quietly caught deep in oclif.
All OclifCommand calls to `this.config.runHook('hook-id', <context-data>)` are await-able, and return an object with 2 arrays, `{failures[], successes[]}`
We need to read failures and exit if appropriate.

**To Reproduce**
1. write a hook responder that gets called
2. throw an error from your hook responder
3. observe that the cli command continues as if nothing happened

**Expected behavior**
- clear log message identifying the plugin where the error occurred
- clear log message identifying what went wrong and how to correct it

### PR DESCRIPTION
**Pull request by purplecabbage**
Closes #665

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/commands/app/deploy.js [hunk 1]
```diff
@@ -146,7 +146,11 @@ class Deploy extends BuildCommand {
 
       if (flags['feature-event-hooks']) {
         this.log('feature-event-hooks is enabled, running pre-deploy-event-reg hook')
-        await this.config.runHook('pre-deploy-event-reg', { appConfig: config })
+        const hookResults = await this.config.runHook('pre-deploy-event-reg', { appConfig: config })
+        if (hookResults?.failures?.length > 0) {
+          // output should be "Error : <plugin-name> : <error-message>\n" for each failure
+          this.error(hookResults.failures.map(f => `${f.plugin.name} : ${f.error.message}`).join('\nError: '), { exit: 1 })
```
Comment (shazron) [inline src/commands/app/deploy.js:152]: Do we want to extract this into a function in the class? Since it is duplicated thrice

Comment (purplecabbage) [reply src/commands/app/deploy.js:152]: its not exactly the same all 3 times
if we need to write it 5 times I'll consider it, or if it expands into more than 1 line.

**Comment by sangeetha5491** [comment]
LGTM
