### PR TITLE
fix: ACNA-1839 - not properly showing templates only supported by my org

### LINKED ISSUE #600: not properly showing templates only supported by my org
## Description

`aio-cli@9.1.0`

My Org has the AssetComputeSDK service, but when I select `Only Templates Supported By My Org` I don't see the template `@adobe/generator-app-asset-compute`.

## Repro

1. aio app init my-app
2. Select an Org that has AssetComputeSDK
3. Select a Project
4. Choose `Only Templates Supported By My Org`

No template `@adobe/generator-app-asset-compute` is listed in the template chooser.

## Expected

Able to select `@adobe/generator-app-asset-compute` that is listed in the template chooser for `Only Templates Supported By My Org`.

## Workaround

Instead of choosing `Only Templates Supported By My Org`, select `All Templates` and choose the `@adobe/generator-app-asset-compute` template there.

## Investigation

When querying for templates with certain `apis`, the query is such:
`?apis=|A,|B`  (note the pipe '|' operator which signifies an `OR` clause)

The actual query should omit the pipe operator for the first item, like so:
`?apis=A,|B`

### PR DESCRIPTION
**Pull request by shazron**
Fixes #600 

## How Has This Been Tested?

- npm test
- manual test via `aio plugins link .`

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by MichaelGoberling — APPROVED** [review]

File: src/commands/app/init.js [hunk 1]
```diff
@@ -250,7 +250,10 @@ class InitCommand extends TemplatesCommand {
 
     switch (selection) {
       case 'orgTemplates': {
-        const supportedServiceCodes = new Set(orgSupportedServices.map(s => `|${s.code}`)) // | symbol denotes an OR clause
+        const supportedServiceCodes = new Set(orgSupportedServices.map((elem, index) => {
+          const operator = index > 0 ? '|' : '' // | symbol denotes an OR clause (only if it's not the first item)
+          return `${operator}${elem.code}`
```
Comment (sandeep-paliwal) [inline src/commands/app/init.js:255]: Should we add tests to verify this formatted o/p?

Comment (shazron) [reply src/commands/app/init.js:255]: Good idea, will add

Comment (shazron) [reply src/commands/app/init.js:255]: Done
